name: Code Review with OpenAI
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INFERENCE_API_KEY: ${{ secrets.INFERENCE_API_KEY }}
          MODEL: "claude-3-5-sonnet-20240620"
          exclude: "yarn.lock, dist/**"
          custom_instructions: "Ignore logging changes, Only focus on important changes"
